spring:
  application:
    name: mentor-service
  datasource:
    url: jdbc:postgresql://localhost:54320/
    driver-class-name: org.postgresql.Driver
    username: user
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true




server:
  port: 8082